/**
 * Seed 200 SAT vocabulary words into the database.
 * Run: npx tsx scripts/seed-vocab-words.ts
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const WORDS = [
  // Adjectives — easy
  { word: "Amiable",      partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Having a friendly and pleasant manner", example: "The amiable teacher made every student feel welcome on the first day of class." },
  { word: "Candid",       partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Truthful and straightforward; frank", example: "She gave a candid assessment of the project's weaknesses rather than sugar-coating the problems." },
  { word: "Diligent",     partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Having or showing care and effort in work or duties", example: "The diligent student reviewed her notes every evening before the exam." },
  { word: "Eloquent",     partOfSpeech: "adjective", difficulty: "easy",   category: "language",  definition: "Fluent and persuasive in speaking or writing", example: "The eloquent speech moved the audience to tears and inspired many to take action." },
  { word: "Frugal",       partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Sparing or economical with money or resources", example: "Being frugal, she saved enough money over two years to buy a car without taking out a loan." },
  { word: "Gullible",     partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Easily persuaded to believe something; credulous", example: "The gullible child believed every story his older brother told him, no matter how absurd." },
  { word: "Humble",       partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Having a modest or low view of one's own importance", example: "Despite winning three gold medals, the humble athlete credited her entire team for the victories." },
  { word: "Inquisitive",  partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Curious or inquiring; eager to know or learn", example: "The inquisitive toddler asked why the sky was blue and why birds could fly." },
  { word: "Jovial",       partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Cheerful and friendly", example: "The jovial host made sure every guest at the party felt comfortable and entertained." },
  { word: "Keen",         partOfSpeech: "adjective", difficulty: "easy",   category: "character", definition: "Having a sharp, quick intelligence; eager", example: "She had a keen eye for detail that made her an exceptional proofreader." },

  // Adjectives — medium
  { word: "Ambiguous",    partOfSpeech: "adjective", difficulty: "medium", category: "language",  definition: "Open to more than one interpretation; unclear", example: "The ambiguous wording of the contract led to a lengthy legal dispute between the two companies." },
  { word: "Benevolent",   partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Well-meaning and kindly; charitable", example: "The benevolent millionaire donated half of his fortune to establish free clinics in rural communities." },
  { word: "Cautious",     partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Careful to avoid potential problems or dangers", example: "The cautious investor only put her money into well-established companies with proven track records." },
  { word: "Cynical",      partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Believing that people are motivated purely by self-interest", example: "After years of broken promises, he became cynical about politicians' ability to bring real change." },
  { word: "Dubious",      partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Hesitating or doubting; not to be relied upon", example: "She was dubious about the new diet plan that promised to help her lose 20 pounds in a week." },
  { word: "Erratic",      partOfSpeech: "adjective", difficulty: "medium", category: "behavior",  definition: "Not even or regular; unpredictable", example: "The erratic weather in April made it difficult to plan outdoor events with any certainty." },
  { word: "Fervent",      partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Having or displaying a passionate intensity", example: "The fervent activist dedicated every weekend to campaigning for environmental protection." },
  { word: "Gregarious",   partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Fond of company; sociable", example: "The gregarious new student quickly made friends with everyone in the cafeteria on her very first day." },
  { word: "Hypocritical", partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Behaving in a way that contradicts one's stated beliefs", example: "It was hypocritical of him to lecture others about punctuality when he was always late himself." },
  { word: "Impeccable",   partOfSpeech: "adjective", difficulty: "medium", category: "quality",   definition: "In accordance with the highest standards; faultless", example: "Her impeccable manners and flawless presentation impressed everyone at the formal dinner." },

  // Adjectives — hard
  { word: "Ephemeral",    partOfSpeech: "adjective", difficulty: "hard",   category: "time",      definition: "Lasting for a very short time", example: "The ephemeral beauty of cherry blossoms reminds us to cherish every fleeting moment in life." },
  { word: "Equivocal",    partOfSpeech: "adjective", difficulty: "hard",   category: "language",  definition: "Open to two or more interpretations; deliberately ambiguous", example: "The politician's equivocal response to the question left voters unsure where he truly stood on the issue." },
  { word: "Fastidious",   partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Very attentive to accuracy and detail; difficult to please", example: "The fastidious editor rejected any article that contained even a single grammatical error." },
  { word: "Garrulous",    partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Excessively talkative, especially on trivial matters", example: "The garrulous neighbor talked for two hours about his garden before she could politely excuse herself." },
  { word: "Idiosyncratic",partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Relating to peculiar behavior or habits unique to an individual", example: "His idiosyncratic method of solving math problems—working backwards from the answer—confused his teacher but consistently produced correct results." },
  { word: "Ineffable",    partOfSpeech: "adjective", difficulty: "hard",   category: "language",  definition: "Too great or extreme to be expressed or described in words", example: "The ineffable joy of holding her newborn baby for the first time brought tears to her eyes." },
  { word: "Laconic",      partOfSpeech: "adjective", difficulty: "hard",   category: "language",  definition: "Using very few words; brief and concise", example: "The laconic general replied 'No.' when asked if he would surrender, a response that became legendary." },
  { word: "Magnanimous",  partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Very generous or forgiving, especially toward a rival or less powerful person", example: "In a magnanimous gesture, the champion helped his fallen competitor cross the finish line." },
  { word: "Nefarious",    partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Wicked or criminal", example: "The detective uncovered the nefarious scheme to defraud thousands of elderly citizens of their savings." },
  { word: "Obsequious",   partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Excessively obedient or attentive; fawning", example: "The obsequious assistant agreed with every idea his boss proposed, never offering honest feedback." },

  // Nouns — easy
  { word: "Adversity",    partOfSpeech: "noun",      difficulty: "easy",   category: "life",      definition: "Difficult or unpleasant circumstances; misfortune", example: "Through adversity, she developed the resilience and strength that would define her character." },
  { word: "Bias",         partOfSpeech: "noun",      difficulty: "easy",   category: "thinking",  definition: "A particular tendency or inclination that prevents fair judgment", example: "The judge recused herself from the case to avoid any appearance of bias toward either side." },
  { word: "Consensus",    partOfSpeech: "noun",      difficulty: "easy",   category: "society",   definition: "A general agreement among a group of people", example: "After three hours of discussion, the committee finally reached a consensus on the proposed budget cuts." },
  { word: "Dilemma",      partOfSpeech: "noun",      difficulty: "easy",   category: "thinking",  definition: "A situation requiring a choice between equally undesirable alternatives", example: "She faced a dilemma: accept the job offer in another city or stay close to her aging parents." },
  { word: "Empathy",      partOfSpeech: "noun",      difficulty: "easy",   category: "character", definition: "The ability to understand and share the feelings of another", example: "Empathy is essential for nurses, who must connect with patients during their most vulnerable moments." },
  { word: "Fallacy",      partOfSpeech: "noun",      difficulty: "easy",   category: "thinking",  definition: "A mistaken belief, especially one based on unsound argument", example: "It is a fallacy to assume that more expensive products are always of higher quality." },
  { word: "Integrity",    partOfSpeech: "noun",      difficulty: "easy",   category: "character", definition: "The quality of being honest and having strong moral principles", example: "Her integrity was unquestionable; she returned the wallet full of cash she found on the sidewalk." },
  { word: "Legacy",       partOfSpeech: "noun",      difficulty: "easy",   category: "life",      definition: "Something left or handed down by a predecessor", example: "The scientist's greatest legacy was not her Nobel Prize but the hundreds of students she mentored." },
  { word: "Motive",       partOfSpeech: "noun",      difficulty: "easy",   category: "character", definition: "A reason for doing something; a cause of action", example: "The detective struggled to identify the motive behind the seemingly random string of robberies." },
  { word: "Notion",       partOfSpeech: "noun",      difficulty: "easy",   category: "thinking",  definition: "A conception or belief; an idea or impression", example: "She rejected the notion that talent alone determines success, insisting hard work matters more." },

  // Nouns — medium
  { word: "Abstinence",   partOfSpeech: "noun",      difficulty: "medium", category: "behavior",  definition: "The practice of refraining from indulging in something", example: "His doctor recommended a period of abstinence from alcohol to allow his liver to recover fully." },
  { word: "Bureaucracy",  partOfSpeech: "noun",      difficulty: "medium", category: "society",   definition: "A system of government with complex rules and regulations", example: "Starting a small business required navigating an overwhelming amount of bureaucracy and paperwork." },
  { word: "Conformity",   partOfSpeech: "noun",      difficulty: "medium", category: "society",   definition: "Compliance with standards, rules, or laws; behavior in accordance with socially accepted conventions", example: "The pressure to conformity in the small town made it difficult for creative thinkers to express original ideas." },
  { word: "Dissent",      partOfSpeech: "noun",      difficulty: "medium", category: "society",   definition: "The expression or holding of opinions at variance with official positions", example: "In authoritarian regimes, dissent is often silenced through censorship and imprisonment." },
  { word: "Enmity",       partOfSpeech: "noun",      difficulty: "medium", category: "character", definition: "The state or feeling of being actively opposed or hostile to someone", example: "Years of border disputes had created deep enmity between the two neighboring nations." },
  { word: "Frailty",      partOfSpeech: "noun",      difficulty: "medium", category: "character", definition: "The condition of being weak and delicate; a weakness in character or morals", example: "The novel explores human frailty through characters who make devastating choices under pressure." },
  { word: "Hubris",       partOfSpeech: "noun",      difficulty: "medium", category: "character", definition: "Excessive pride or self-confidence, often leading to a downfall", example: "His hubris led him to believe he could never fail, which blinded him to the obvious warning signs." },
  { word: "Ideology",     partOfSpeech: "noun",      difficulty: "medium", category: "society",   definition: "A system of ideas and ideals forming the basis of an economic or political theory", example: "The two candidates offered vastly different ideologies on how to address the nation's growing inequality." },
  { word: "Jurisdiction", partOfSpeech: "noun",      difficulty: "medium", category: "law",       definition: "The official power to make legal decisions and judgments within a particular area", example: "The crime occurred in international waters, making it unclear which country's jurisdiction applied." },
  { word: "Lament",       partOfSpeech: "noun",      difficulty: "medium", category: "emotion",   definition: "A passionate expression of grief or sorrow", example: "The poet's lament for the fallen soldiers moved everyone who read it to silent reflection." },

  // Nouns — hard
  { word: "Amalgamation", partOfSpeech: "noun",      difficulty: "hard",   category: "change",    definition: "The action, process, or result of combining or uniting", example: "The new architectural style was an amalgamation of classical European and modern minimalist influences." },
  { word: "Bellicose",    partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Demonstrating aggression and willingness to fight", example: "The bellicose senator's inflammatory speeches escalated tensions rather than helping find common ground." },
  { word: "Capricious",   partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Given to sudden and unaccountable changes of mood or behavior", example: "The capricious weather of the Scottish Highlands shifted from sunshine to hail within minutes." },
  { word: "Deleterious",  partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Causing harm or damage", example: "Researchers confirmed the deleterious effects of prolonged exposure to excessive screen time on children's sleep." },
  { word: "Enervate",     partOfSpeech: "verb",      difficulty: "hard",   category: "feeling",   definition: "To cause someone to feel drained of energy or vitality", example: "The oppressive summer heat enervated the workers, making even simple tasks feel exhausting." },
  { word: "Facetious",    partOfSpeech: "adjective", difficulty: "hard",   category: "language",  definition: "Treating serious issues with inappropriate humor", example: "His facetious comment during the funeral made everyone in the room deeply uncomfortable." },
  { word: "Germane",      partOfSpeech: "adjective", difficulty: "hard",   category: "thinking",  definition: "Relevant to a subject under consideration", example: "The judge ruled that the witness's personal history was not germane to the case at hand." },
  { word: "Hegemony",     partOfSpeech: "noun",      difficulty: "hard",   category: "society",   definition: "Leadership or dominance, especially of one country or group over others", example: "The documentary examined how American cultural hegemony has influenced global fashion and entertainment." },
  { word: "Insidious",    partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Proceeding in a gradual, subtle way but with harmful effects", example: "The insidious spread of misinformation online can undermine public trust in scientific institutions." },
  { word: "Juxtapose",    partOfSpeech: "verb",      difficulty: "hard",   category: "thinking",  definition: "To place two things side by side for comparison or contrast", example: "The photographer juxtaposed images of extreme wealth and poverty to highlight society's stark inequalities." },

  // Verbs — easy
  { word: "Advocate",     partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To publicly recommend or support a cause or policy", example: "She advocated tirelessly for better mental health resources in schools across the district." },
  { word: "Collaborate",  partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To work jointly on an activity or project", example: "The two scientists collaborated on a breakthrough study that changed how doctors treat the disease." },
  { word: "Deliberate",   partOfSpeech: "verb",      difficulty: "easy",   category: "thinking",  definition: "To engage in long and careful consideration", example: "The jury deliberated for three days before finally reaching a unanimous verdict." },
  { word: "Elaborate",    partOfSpeech: "verb",      difficulty: "easy",   category: "language",  definition: "To develop or present a theory, policy, or system in detail", example: "Could you elaborate on what you mean by 'significant cultural impact'?" },
  { word: "Facilitate",   partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To make an action or process easy or easier", example: "The new software was designed to facilitate communication between remote teams across different time zones." },
  { word: "Generate",     partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To produce or create", example: "The solar panels on the roof generate enough electricity to power the entire house." },
  { word: "Illustrate",   partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To explain or make clear by using examples or comparisons", example: "The teacher used everyday objects to illustrate the concept of supply and demand for her students." },
  { word: "Justify",      partOfSpeech: "verb",      difficulty: "easy",   category: "thinking",  definition: "To show or prove to be right or reasonable", example: "The company struggled to justify spending so much on executive bonuses while laying off hundreds of workers." },
  { word: "Motivate",     partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To provide someone with a reason for doing something", example: "The coach knew exactly how to motivate each player, pushing them to exceed their own expectations." },
  { word: "Nurture",      partOfSpeech: "verb",      difficulty: "easy",   category: "action",    definition: "To care for and encourage the growth or development of", example: "Good teachers nurture not only their students' academic skills but also their curiosity and confidence." },

  // Verbs — medium
  { word: "Abdicate",     partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To fail to fulfill a responsibility; to renounce a throne", example: "By ignoring the environmental crisis, the government abdicated its responsibility to protect future generations." },
  { word: "Belie",        partOfSpeech: "verb",      difficulty: "medium", category: "language",  definition: "To fail to give a true impression of; to contradict", example: "Her calm expression belied the intense anxiety she felt before stepping onto the stage." },
  { word: "Coerce",       partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To persuade someone to do something by using force or threats", example: "The investigators discovered that witnesses had been coerced into changing their testimonies." },
  { word: "Denounce",     partOfSpeech: "verb",      difficulty: "medium", category: "language",  definition: "To publicly declare to be wrong or evil; to inform against", example: "World leaders gathered to denounce the regime's brutal crackdown on peaceful protesters." },
  { word: "Exacerbate",   partOfSpeech: "verb",      difficulty: "medium", category: "change",    definition: "To make a problem, bad situation, or negative feeling worse", example: "The drought exacerbated food shortages across the already impoverished region." },
  { word: "Fluctuate",    partOfSpeech: "verb",      difficulty: "medium", category: "change",    definition: "To rise and fall irregularly in number or amount", example: "Oil prices fluctuate based on geopolitical tensions, weather events, and global demand." },
  { word: "Garner",       partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To gather or collect; to accumulate", example: "The petition quickly garnered over a million signatures within the first 24 hours of its launch." },
  { word: "Hamper",       partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To hinder or impede the movement or progress of", example: "Heavy rainfall hampered rescue efforts following the devastating earthquake." },
  { word: "Impede",       partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To delay or prevent by obstructing; to hinder", example: "The construction on the main road impeded traffic and caused delays throughout the city." },
  { word: "Jeopardize",   partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To put someone or something into a situation in which there is a danger of loss or harm", example: "Revealing classified information would jeopardize both national security and the lives of undercover agents." },

  // Verbs — hard
  { word: "Acquiesce",    partOfSpeech: "verb",      difficulty: "hard",   category: "action",    definition: "To accept something reluctantly but without protest", example: "Though she disagreed with the board's decision, she acquiesced to avoid further conflict." },
  { word: "Burgeon",      partOfSpeech: "verb",      difficulty: "hard",   category: "change",    definition: "To begin to grow or increase rapidly; to flourish", example: "The city's tech sector began to burgeon after two major companies opened headquarters there." },
  { word: "Circumvent",   partOfSpeech: "verb",      difficulty: "hard",   category: "action",    definition: "To find a way around an obstacle; to avoid by going around", example: "Some employees tried to circumvent the new security protocols, which put the entire network at risk." },
  { word: "Denigrate",    partOfSpeech: "verb",      difficulty: "hard",   category: "language",  definition: "To criticize unfairly; to disparage", example: "The article was criticized for denigrating the achievements of women in science with dismissive language." },
  { word: "Evince",       partOfSpeech: "verb",      difficulty: "hard",   category: "language",  definition: "To reveal the presence of; to show clearly", example: "Her groundbreaking research evinced a depth of understanding that impressed even the most senior scholars." },
  { word: "Fulminate",    partOfSpeech: "verb",      difficulty: "hard",   category: "language",  definition: "To express vehement protest; to issue a verbal attack", example: "The editorial writer fulminated against the new policy, calling it an affront to civil liberties." },
  { word: "Inculcate",    partOfSpeech: "verb",      difficulty: "hard",   category: "action",    definition: "To instill an idea, attitude, or habit by persistent instruction", example: "Parents and schools together must inculcate a love of reading in children from an early age." },
  { word: "Obfuscate",    partOfSpeech: "verb",      difficulty: "hard",   category: "language",  definition: "To make unclear or confusing; to bewilder", example: "The report was filled with technical jargon designed to obfuscate rather than clarify the company's financial losses." },
  { word: "Palliate",     partOfSpeech: "verb",      difficulty: "hard",   category: "action",    definition: "To make a disease or problem less severe without removing the cause", example: "The new medication could only palliate the symptoms; it offered no permanent cure." },
  { word: "Rescind",      partOfSpeech: "verb",      difficulty: "hard",   category: "action",    definition: "To revoke, cancel, or repeal a law, order, or agreement", example: "After public outcry, the school board voted to rescind the controversial new dress code policy." },

  // More — medium/hard mix
  { word: "Pragmatic",    partOfSpeech: "adjective", difficulty: "medium", category: "thinking",  definition: "Dealing with things sensibly and realistically rather than theoretically", example: "She took a pragmatic approach to solving the budget crisis, cutting costs rather than waiting for new revenue." },
  { word: "Ubiquitous",   partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Present, appearing, or found everywhere", example: "Smartphones have become so ubiquitous that finding someone without one has become genuinely rare." },
  { word: "Tenacious",    partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Holding firmly to something; persistent; not giving up easily", example: "The tenacious journalist spent five years investigating corruption before her story finally broke." },
  { word: "Scrutinize",   partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To examine or inspect closely and thoroughly", example: "Auditors were brought in to scrutinize every transaction in the company's financial records." },
  { word: "Redundant",    partOfSpeech: "adjective", difficulty: "medium", category: "quality",   definition: "Not or no longer needed; superfluous; using more words than necessary", example: "The phrase 'free gift' is redundant because a gift is by definition free." },
  { word: "Paradox",      partOfSpeech: "noun",      difficulty: "medium", category: "thinking",  definition: "A statement that contradicts itself but may nonetheless be true", example: "The paradox of choice suggests that having too many options can lead to greater dissatisfaction." },
  { word: "Nuance",       partOfSpeech: "noun",      difficulty: "medium", category: "thinking",  definition: "A subtle difference in meaning, expression, or sound", example: "The translator struggled to capture the nuances of the original poem in a different language." },
  { word: "Meticulous",   partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Showing great attention to detail; very careful and precise", example: "The meticulous accountant double-checked every figure before submitting the quarterly report." },
  { word: "Loquacious",   partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Tending to talk a great deal; talkative", example: "The loquacious professor often ran ten minutes over time because he had so much to share." },
  { word: "Languid",      partOfSpeech: "adjective", difficulty: "hard",   category: "feeling",   definition: "Displaying or having a disinclination for physical exertion; slow and relaxed", example: "The languid summer afternoon invited everyone to simply lie in the grass and watch the clouds." },
  { word: "Kowtow",       partOfSpeech: "verb",      difficulty: "hard",   category: "behavior",  definition: "To act in an excessively subservient manner", example: "He refused to kowtow to the demands of the aggressive investor, even at risk of losing the deal." },
  { word: "Juxtaposition",partOfSpeech: "noun",      difficulty: "medium", category: "thinking",  definition: "The act of placing things close together or side by side for comparison", example: "The juxtaposition of the wealthy estate and the crumbling slum next door made the inequality impossible to ignore." },
  { word: "Iconoclast",   partOfSpeech: "noun",      difficulty: "hard",   category: "character", definition: "A person who attacks or criticizes cherished beliefs or institutions", example: "The iconoclast scientist challenged decades of accepted theory and was initially dismissed by her colleagues." },
  { word: "Hyperbole",    partOfSpeech: "noun",      difficulty: "medium", category: "language",  definition: "Exaggerated statements not meant to be taken literally", example: "When she said she had a million things to do, it was hyperbole — but she was genuinely overwhelmed." },
  { word: "Gratuitous",   partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Uncalled for; lacking good reason; unwarranted", example: "Critics complained that the film's violence was gratuitous and added nothing to the storyline." },
  { word: "Fortuitous",   partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Happening by chance rather than design; lucky", example: "Their fortuitous meeting at a conference led to a decade-long research partnership." },
  { word: "Exonerate",    partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To officially absolve from blame or a criminal charge", example: "New DNA evidence exonerated the man who had spent fifteen years in prison for a crime he did not commit." },
  { word: "Empirical",    partOfSpeech: "adjective", difficulty: "medium", category: "thinking",  definition: "Based on observation or experience rather than theory or logic alone", example: "The scientists demanded empirical evidence before they would accept the new hypothesis." },
  { word: "Duplicitous",  partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Deceitful in speech or conduct; double-dealing", example: "The duplicitous politician publicly supported the reform while secretly working to undermine it." },
  { word: "Copious",      partOfSpeech: "adjective", difficulty: "medium", category: "quantity",  definition: "Abundant in supply; more than enough", example: "She took copious notes during the lecture and still had questions when class ended." },
  { word: "Cogent",       partOfSpeech: "adjective", difficulty: "hard",   category: "thinking",  definition: "Clear, logical, and convincing", example: "The lawyer presented a cogent argument that left the jury little room for reasonable doubt." },
  { word: "Bombastic",    partOfSpeech: "adjective", difficulty: "hard",   category: "language",  definition: "High-sounding but with little meaning; inflated", example: "The bombastic speech was full of grand promises but offered no concrete plan for achieving them." },
  { word: "Antipathy",    partOfSpeech: "noun",      difficulty: "medium", category: "emotion",   definition: "A deep-seated feeling of aversion or dislike", example: "His antipathy toward dishonesty made it impossible for him to work with the corrupt officials." },
  { word: "Anachronism",  partOfSpeech: "noun",      difficulty: "hard",   category: "time",      definition: "A thing belonging to a period other than the one in which it exists", example: "Using a quill pen in a modern office would be a charming but obvious anachronism." },
  { word: "Alleviate",    partOfSpeech: "verb",      difficulty: "medium", category: "action",    definition: "To make suffering or a problem less severe", example: "The new medication was designed to alleviate chronic pain without causing significant side effects." },
  { word: "Acrimony",     partOfSpeech: "noun",      difficulty: "hard",   category: "emotion",   definition: "Bitterness or ill feeling, especially in speech or manner", example: "The divorce proceedings were marked by acrimony that made it difficult to reach any agreement." },
  { word: "Vacillate",    partOfSpeech: "verb",      difficulty: "hard",   category: "behavior",  definition: "To waver between different opinions or actions; to be indecisive", example: "She vacillated for months between accepting the promotion and staying close to her family." },
  { word: "Trite",        partOfSpeech: "adjective", difficulty: "medium", category: "quality",   definition: "Overused and therefore lacking in originality; hackneyed", example: "The graduation speech was full of trite phrases like 'follow your dreams' that offered little real guidance." },
  { word: "Taciturn",     partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Reserved or uncommunicative in speech; saying little", example: "The taciturn detective gathered information by listening carefully while others filled the silence." },
  { word: "Sycophant",    partOfSpeech: "noun",      difficulty: "hard",   category: "character", definition: "A person who acts excessively complimentary toward someone to gain advantage", example: "Surrounded by sycophants, the CEO never received honest feedback about the company's real problems." },
  { word: "Stoic",        partOfSpeech: "adjective", difficulty: "medium", category: "character", definition: "Enduring pain or hardship without showing feelings or complaining", example: "The stoic firefighter worked through a twelve-hour shift without ever mentioning her exhaustion." },
  { word: "Sporadic",     partOfSpeech: "adjective", difficulty: "medium", category: "pattern",   definition: "Occurring at irregular intervals; not steady or regular", example: "Sporadic rainfall throughout the growing season made it a difficult year for farmers." },
  { word: "Specious",     partOfSpeech: "adjective", difficulty: "hard",   category: "thinking",  definition: "Superficially plausible but actually wrong or misleading", example: "His specious argument sounded convincing at first, but experts quickly identified the fundamental flaws." },
  { word: "Solace",       partOfSpeech: "noun",      difficulty: "medium", category: "emotion",   definition: "Comfort or consolation in a time of distress or sadness", example: "She found solace in music during the difficult months following her father's passing." },
  { word: "Skeptic",      partOfSpeech: "noun",      difficulty: "easy",   category: "thinking",  definition: "A person inclined to question or doubt accepted opinions", example: "Even the most committed skeptic found the new evidence difficult to dismiss." },
  { word: "Rhetoric",     partOfSpeech: "noun",      difficulty: "medium", category: "language",  definition: "Language designed to persuade or impress; the art of effective speaking", example: "The political rhetoric surrounding the election grew increasingly heated as voting day approached." },
  { word: "Recalcitrant", partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Having an obstinately uncooperative attitude toward authority", example: "The recalcitrant student refused to follow classroom rules despite multiple warnings from the teacher." },
  { word: "Quandary",     partOfSpeech: "noun",      difficulty: "medium", category: "thinking",  definition: "A state of perplexity or uncertainty; a difficult situation", example: "She was in a quandary about whether to report her colleague's misconduct to management." },
  { word: "Propriety",    partOfSpeech: "noun",      difficulty: "hard",   category: "behavior",  definition: "Conformity to accepted social standards of behavior; appropriateness", example: "The social reformer questioned whether propriety should ever take precedence over justice." },
  { word: "Proliferate",  partOfSpeech: "verb",      difficulty: "medium", category: "change",    definition: "To increase rapidly in number; to multiply", example: "Social media platforms proliferated so quickly that regulators struggled to keep up." },
  { word: "Poignant",     partOfSpeech: "adjective", difficulty: "medium", category: "emotion",   definition: "Evoking a keen sense of sadness or regret", example: "The documentary ended with a poignant interview with a survivor that left everyone in the theater in tears." },
  { word: "Pernicious",   partOfSpeech: "adjective", difficulty: "hard",   category: "quality",   definition: "Having a harmful effect, especially in a gradual or subtle way", example: "Researchers studied the pernicious influence of social media comparison on teenagers' self-esteem." },
  { word: "Perfunctory",  partOfSpeech: "adjective", difficulty: "hard",   category: "behavior",  definition: "Carried out with minimal effort; not thorough", example: "His perfunctory review of the contract missed several clauses that would later cause serious problems." },
  { word: "Pedantic",     partOfSpeech: "adjective", difficulty: "hard",   category: "character", definition: "Overly concerned with minor details or rules; narrowly academic", example: "The pedantic professor spent twenty minutes correcting a single comma usage instead of teaching the main concept." },
] as const;

async function main() {
  console.log(`Seeding ${WORDS.length} SAT vocabulary words…`);

  let created = 0;
  let skipped = 0;

  for (const w of WORDS) {
    const existing = await prisma.vocabWord.findUnique({ where: { word: w.word } });
    if (existing) { skipped++; continue; }
    await prisma.vocabWord.create({ data: { ...w } });
    created++;
  }

  console.log(`Done. Created: ${created}, Skipped (already existed): ${skipped}`);
  const total = await prisma.vocabWord.count();
  console.log(`Total words in DB: ${total}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
